### ISSUE TITLE
Implement ui to Initialize game

### ISSUE THREAD

**Issue by FernandezRobert** [fjprog101/at18#132]
**As a** Developer, **I want** to create the initial user interface to begin the game, **so that** I can choose the total of players and their monsters to begin the game.

**Acceptance Criteria:**

**Given** the total amount of players in a ui **AND**
          for now, there are 2 players
**When** it clicks on the "next" button
**Then** then it should show you a new window to register the first player.

**Given** The information of the first player  **AND**
          that player chooses its monster
**When** it clicks on the "next" button
**Then** then it should show you a new window to register a second player.

**Given** The information of the second player  **AND**
          that player chooses its monster
**When** it clicks on the "start" button
**Then** then it should show you a new window to begin the game.

**Tasks**
- [x] Implement UI for choosing the number of players (@FernandezRobert)
- [ ] Implement the functionality for choosing the number of players (@FernandezRobert)
- [x] Implement UI for choosing the first players info (@FernandezRobert)
- [ ] Implement the functionality for choosing the first players info (@FernandezRobert)
- [x] Implement UI for choosing the second players info (@FernandezRobert)
- [ ] Implement the functionality for choosing the second players info (@FernandezRobert)
